ExUnit.start()
Code.require_file("support/extensions_audit_fixture.exs", __DIR__)
Code.require_file("support/extension_host_fixtures.exs", __DIR__)
Code.require_file("support/snapshot_support.exs", __DIR__)
Code.require_file("support/test_support.exs", __DIR__)
