#!/usr/bin/env python3
"""Bootstrap reusable agentic delivery assets into a project repo.

This CLI is intentionally small and dependency-free so any future agent can run
it from a fresh checkout. It installs workflow/process assets and records stack
choices; it does not assume LuxeBook's stack or generate product code by
default.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import stat
import sys
from dataclasses import dataclass
from pathlib import Path


STACK_DEFAULT = "next-nest-prisma-postgres-redis"
DEPLOY_DEFAULT = "vercel-plus-managed-backend"


@dataclass(frozen=True)
class PackagePaths:
    root: Path
    skill: Path
    template_root: Path
    stack_root: Path
    deploy_root: Path
    feature_pack_root: Path


def package_paths() -> PackagePaths:
    root = Path(__file__).resolve().parents[1]
    skill = root / "skills" / "agentic-delivery-loop"
    top_level_templates = root / "templates"
    nested_templates = skill / "assets" / "templates"
    template_root = top_level_templates if top_level_templates.exists() else nested_templates

    return PackagePaths(
        root=root,
        skill=skill,
        template_root=template_root,
        stack_root=root / "project-templates" / "stacks",
        deploy_root=root / "project-templates" / "deploy",
        feature_pack_root=root / "project-templates" / "feature-packs",
    )


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "-", value.strip()).strip("-").lower()
    return slug or "new-project"


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str, *, overwrite: bool, dry_run: bool) -> str:
    if path.exists() and not overwrite:
        return f"skip existing {path}"
    if dry_run:
        return f"would write {path}"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return f"wrote {path}"


def copy_tree(src: Path, dst: Path, *, overwrite: bool, dry_run: bool) -> str:
    if dst.exists() and not overwrite:
        return f"skip existing {dst}"
    if dry_run:
        return f"would copy {src} -> {dst}"
    if dst.exists():
        shutil.rmtree(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(src, dst)
    return f"copied {src} -> {dst}"


def copy_file(src: Path, dst: Path, *, overwrite: bool, dry_run: bool) -> str:
    if dst.exists() and not overwrite:
        return f"skip existing {dst}"
    if dry_run:
        return f"would copy {src} -> {dst}"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return f"copied {src} -> {dst}"


def make_executable(path: Path, *, dry_run: bool) -> None:
    if dry_run or not path.exists():
        return
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def profile_exists(root: Path, name: str) -> bool:
    return (root / f"{name}.yml").exists()


def profile_summary(root: Path) -> list[tuple[str, str]]:
    profiles: list[tuple[str, str]] = []
    if not root.exists():
        return profiles
    for path in sorted(root.glob("*.yml")):
        description = ""
        for line in read_text(path).splitlines():
            if line.startswith("description:"):
                description = line.split(":", 1)[1].strip().strip('"')
                break
        profiles.append((path.stem, description))
    return profiles


def render_workflow(template: str, project_slug: str, linear_project_slug: str) -> str:
    workflow = template.replace("<project>", project_slug)
    workflow = workflow.replace("<linear-project-slug>", linear_project_slug or "replace-me")
    return workflow


def render_manifest(args: argparse.Namespace, project_slug: str) -> str:
    feature_packs = args.feature_pack or []
    feature_pack_lines = "\n".join(f"  - {yaml_quote(pack)}" for pack in feature_packs) or "  []"
    return f"""# Generated by agentic_project.py. Edit this file as the project evolves.
project:
  name: {yaml_quote(args.project_name)}
  slug: {yaml_quote(project_slug)}

agentic_delivery:
  skill_mode: {yaml_quote(args.skill_mode)}
  miu_execution_doc: ".codex/agentic/miu-execution.md"
  linear_workstream_template: ".codex/agentic/linear-workstream.md"
  symphony_workflow: ".codex/symphony/WORKFLOW.concurrent-symphony.md"

stack:
  profile: {yaml_quote(args.stack)}
  notes: "Profile records defaults only; verify against real product constraints before implementation."

deployment:
  profile: {yaml_quote(args.deploy)}
  notes: "Deployment profile is selectable and replaceable per project."

workflow:
  mode: {yaml_quote(args.workflow_mode)}
  linear_project_slug: {yaml_quote(args.linear_project_slug or "")}
  symphony_workspace_root: {yaml_quote(args.workspace_root or f"~/.codex/symphony-workspaces/{project_slug}-concurrent")}
  branch_policy: {yaml_quote(args.branch_policy)}

feature_packs:
{feature_pack_lines}

business_boundaries:
  ownership: "TBD"
  actor: "TBD"
  durable_data: "TBD"
  ephemeral_data: "TBD"
  money_value: "TBD"
  time_concurrency: "TBD"
  storage_media: "TBD"
  external_provider: "TBD"
  user_visible_truth: "TBD"
"""


def render_stack_doc(args: argparse.Namespace, project_slug: str, paths: PackagePaths) -> str:
    stack_profile = paths.stack_root / f"{args.stack}.yml"
    deploy_profile = paths.deploy_root / f"{args.deploy}.yml"
    feature_packs = args.feature_pack or []
    feature_pack_docs = []
    for pack in feature_packs:
        path = paths.feature_pack_root / f"{pack}.yml"
        if path.exists():
            feature_pack_docs.append(f"## Feature Pack: {pack}\n\n```yaml\n{read_text(path).strip()}\n```\n")

    return f"""# Project Stack

Project: `{args.project_name}` (`{project_slug}`)

This document records the starting template choices. It is not a frozen
architecture contract. Update it when the real project chooses a different
stack, provider, deployment shape, or business boundary.

## Selected Stack

```yaml
{read_text(stack_profile).strip()}
```

## Selected Deployment

```yaml
{read_text(deploy_profile).strip()}
```

{''.join(feature_pack_docs) if feature_pack_docs else '## Feature Packs\n\nNo feature packs selected yet.\n'}
## Agent Workflow

- Skill: `agentic-delivery-loop`
- MIU trace: `.codex/agentic/miu-execution.md`
- Symphony workflow: `.codex/symphony/WORKFLOW.concurrent-symphony.md`
- Business boundary inventory: fill before implementation.
"""


def render_start_script() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SYMPHONY_REPO="${SYMPHONY_REPO:-$HOME/src/openai-symphony}"
WORKFLOW_FILE="$ROOT/.codex/symphony/WORKFLOW.concurrent-symphony.md"

if [[ ! -d "$SYMPHONY_REPO/elixir" ]]; then
  echo "Missing Symphony Elixir checkout at $SYMPHONY_REPO/elixir" >&2
  exit 1
fi

if [[ -z "${PROJECT_REPO:-}" ]]; then
  PROJECT_REPO="$(git -C "$ROOT" remote get-url origin 2>/dev/null || true)"
fi

if [[ -z "${PROJECT_REPO:-}" ]]; then
  echo "PROJECT_REPO is not set and no git origin remote was found." >&2
  exit 1
fi

export PROJECT_REPO
export PROJECT_BASE_BRANCH="${PROJECT_BASE_BRANCH:-main}"

cd "$SYMPHONY_REPO/elixir"
exec mise exec -- ./bin/symphony "$WORKFLOW_FILE"
"""


def command_list(_args: argparse.Namespace) -> int:
    paths = package_paths()
    print("Stacks:")
    for name, description in profile_summary(paths.stack_root):
        print(f"  {name}: {description}")
    print("\nDeploy profiles:")
    for name, description in profile_summary(paths.deploy_root):
        print(f"  {name}: {description}")
    print("\nFeature packs:")
    for name, description in profile_summary(paths.feature_pack_root):
        print(f"  {name}: {description}")
    return 0


def command_init(args: argparse.Namespace) -> int:
    paths = package_paths()
    repo = Path(args.repo).expanduser().resolve()
    project_slug = slugify(args.project_name or repo.name)
    args.project_name = args.project_name or repo.name

    if not profile_exists(paths.stack_root, args.stack):
        raise SystemExit(f"Unknown stack profile: {args.stack}")
    if not profile_exists(paths.deploy_root, args.deploy):
        raise SystemExit(f"Unknown deploy profile: {args.deploy}")
    for pack in args.feature_pack or []:
        if not profile_exists(paths.feature_pack_root, pack):
            raise SystemExit(f"Unknown feature pack: {pack}")

    operations: list[str] = []

    agents_template = paths.template_root / "AGENTS.next-project.md"
    workflow_template = paths.root / "WORKFLOW.concurrent-symphony.template.md"
    if not workflow_template.exists():
        workflow_template = paths.template_root / "WORKFLOW.concurrent-symphony.template.md"

    operations.append(
        copy_file(
            agents_template,
            repo / "AGENTS.md",
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )
    operations.append(
        copy_file(
            paths.template_root / "miu-execution.md",
            repo / ".codex" / "agentic" / "miu-execution.md",
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )
    operations.append(
        copy_file(
            paths.template_root / "linear-workstream.md",
            repo / ".codex" / "agentic" / "linear-workstream.md",
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )

    if args.skill_mode in {"project", "both"}:
        operations.append(
            copy_tree(
                paths.skill,
                repo / ".codex" / "skills" / "agentic-delivery-loop",
                overwrite=args.force,
                dry_run=args.dry_run,
            )
        )

    operations.append(
        write_text(
            repo / ".codex" / "agentic" / "PROJECT_STACK.yml",
            render_manifest(args, project_slug),
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )
    operations.append(
        write_text(
            repo / "PROJECT_STACK.md",
            render_stack_doc(args, project_slug, paths),
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )
    operations.append(
        write_text(
            repo / ".codex" / "symphony" / "WORKFLOW.concurrent-symphony.md",
            render_workflow(read_text(workflow_template), project_slug, args.linear_project_slug or ""),
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )

    start_script = repo / ".codex" / "symphony" / "start-symphony.sh"
    operations.append(
        write_text(
            start_script,
            render_start_script(),
            overwrite=args.force,
            dry_run=args.dry_run,
        )
    )
    make_executable(start_script, dry_run=args.dry_run)

    for operation in operations:
        print(operation)

    print("\nNext agent action:")
    print("- Read AGENTS.md and PROJECT_STACK.md.")
    print("- Fill the business boundary inventory before implementation.")
    print("- Use the MIU execution doc for the first non-trivial change.")
    print("- If Symphony is requested, set project-specific environment outside git and run .codex/symphony/start-symphony.sh.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Bootstrap agentic delivery assets into a repo.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    list_parser = subparsers.add_parser("list", help="List available stack/deploy profiles.")
    list_parser.set_defaults(func=command_list)

    init_parser = subparsers.add_parser("init", help="Initialize a project with agentic delivery assets.")
    init_parser.add_argument("--repo", default=os.getcwd(), help="Target repository path.")
    init_parser.add_argument("--project-name", default="", help="Human-readable project name.")
    init_parser.add_argument("--stack", default=STACK_DEFAULT, help="Stack profile name.")
    init_parser.add_argument("--deploy", default=DEPLOY_DEFAULT, help="Deployment profile name.")
    init_parser.add_argument("--feature-pack", action="append", default=[], help="Optional feature pack name. Repeatable.")
    init_parser.add_argument("--workflow-mode", default="symphony-linear", help="Workflow mode label.")
    init_parser.add_argument("--linear-project-slug", default="", help="Tracker project slug for generated workflow.")
    init_parser.add_argument("--workspace-root", default="", help="Symphony workspace root to record in manifest.")
    init_parser.add_argument("--branch-policy", default="per-issue-pr", help="Branch/PR policy label.")
    init_parser.add_argument(
        "--skill-mode",
        choices=["global", "project", "both", "none"],
        default="global",
        help="Whether to copy the skill into the target project.",
    )
    init_parser.add_argument("--force", action="store_true", help="Overwrite existing generated files.")
    init_parser.add_argument("--dry-run", action="store_true", help="Show operations without writing files.")
    init_parser.set_defaults(func=command_init)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
